language: node_js
node_js:
  - stable
  - '8'
  - '10'

script:
  - echo "Running tests against $(node -v) ..."
  - npm test

jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        edge: true
        email: ateliee@gmail.com
        access: public
        on:
          branch: master
          tags: true
        api_key:
          secure: paM4UiemNoNDpd5HH5z/nWTaJ0rMIEHKcLXcZ/RFo8zubolcyu1sRvuJVvjUUFdzkeifzBDY6AJgPM4nbrE24RprUH40QmbC7dXhL0quAIsqVY3yEvpyvPzx88SoVgPCl55K/Ium/fD8XnI4ElY9nIurLExDQR/WZcCszNowbLe75YI3GOmvvMYO1CThmABMBKGoYd8DqlhKHQQZu+4Z81tNwTLfRyxp5H/AgSOC/Uw/SkS8sN0y3PcaLlFesKKI+mMyd+uufo9zDDmSngL0/8Nrtag6fSy56tvU1F4ogP3M5bMIaeEu02YGhRcWl0tCP1C8sKM6tgwlvLsdBL2iZ2ak8kFa4wabF1PY/3kaXpjT/xm7bjQ3iY6Q4bRfM23SpyUoCC3kuzqjJ4qCcqHITBShr8Q6z09Nwk4GpGYUlUmvNj1fETLP4YW5NZ/Wmg03e2r4nLnFPFMubz+vqzr9ZESYu+9y2/kutQae01aspdsBjserYiD8HnSE2Nf0tzIPLsDYh7JfwBi7B57e1Wo+yE4EfdFx2s6+uu0aEX82NSlVCKtDtP7SKaK/YTZ/7lA7td1ZuDhZmjuLG0sgDIlg4i5LogKoPgWHEGVcpgOWxqsZt10S7d4xW/FoPIJSnQ9rcPs1HjLTqvBPBPzkqi8NAiFo5s0lIUgfC7+POaeZI5M=
