language: node_js
node_js:
#  - stable
  - '8'
  - '10'
script:
  - echo "Running tests against $(node -v) ..."
  - npm run lint
  - npm test && nyc report --reporter=text-lcov | coveralls

jobs:
  include:
  - stage: npm release
    node_js: '10'
    script: echo "Deploying to npm ..."
    before_deploy: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
    deploy:
      provider: npm
      edge: true
      email: info@ateliee.com
      access: public
      on:
        branch: master
        tags: true
      api_key: $NPM_TOKEN
